repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-yaml
  - repo: local
    hooks:
      - id: pytest-changed
        name: Run pytest on changed tests
        entry: bash -c 'changed=$(git diff --cached --name-only | grep -E "^tests/.*\\.py$" || true); if [ -n "$changed" ]; then python3 -m pytest -q $changed; else echo "No changed tests"; fi'
        language: system
        pass_filenames: false
        types: [python]
