name: UI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'ui/**'
      - '.github/workflows/ui.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'ui/**'

jobs:
  build-test-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json
      - name: Install
        run: npm ci || npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Upload UI dist artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-dist
          path: ui/dist
          if-no-files-found: warn
